server:
  port: 8082
spring:  
  datasource:
    url: jdbc:h2:enursery:ensauth
    driver-class-name: org.h2.Driver
    username: pr
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  
